services:
  - type: web
    name: bot
    runtime: docker
    dockerfilePath: servers/bot/Dockerfile
    buildFilter:
      paths:
        - servers/bot/**/*.ts
        - servers/bot/*.json
        - servers/bot/Dockerfile
    envVars:
      - fromGroup: servers/bot
      - key: APP_URL
        fromService:
          type: web
          name: www
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromDatabase:
          name: safeguardDB
          property: connectionString

  - type: web
    name: www
    runtime: static
    buildCommand: cd web/www && yarn install && yarn build
    staticPublishPath: web/www/dist
    buildFilter:
      paths:
        - web/wwww/**/*.ts
        - web/www/*.json
    envVars:
      - fromGroup: web/www
      - key: VITE_APP_API_URL
        fromService:
          type: web
          name: bot
          envVarKey: RENDER_EXTERNAL_URL
databases:
  - name: safeguardDB
    plan: free