services:
  - type: web
    name: bot
    runtime: node
    plan: free
    buildCommand: cd servers/bot && bun install && bun run build
    startCommand: cd servers/bot && bun migrate && bun run index.ts
    envVars:
      - fromGroup: servers/bot
      - key: APP_URL
        fromService:
          type: web
          name: www
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromDatabase:
          name: safeguardDB
          property: connectionString

  - type: web
    name: www
    runtime: static
    buildCommand: cd web/www && bun install && bun build
    staticPublishPath: cd web/www/dist
    envVars:
      - fromGroup: web/www
      - key: VITE_APP_API_URL
        fromService:
          type: web
          name: bot
          envVarKey: RENDER_EXTERNAL_URL
databases:
  - name: safeguardDB
    plan: free