services:
  - type: web
    name: bot
    runtime: node
    buildCommand: cd servers/bot && bun install && bun run build
    startCommand: cd servers/bot && node dist/index.js
    buildFilter:
      paths:
        - servers/bot/**/*.ts
        - servers/bot/*.json
        - servers/bot/Dockerfile
    envVars:
      - fromGroup: servers/bot
      - key: APP_URL
        value: https://grambot.fun
      - key: DATABASE_URL
        fromDatabase:
          name: safeguardDB
          property: connectionString
    domains:
      - v1.api.grambot.fun

  - type: web
    name: www
    runtime: static
    buildCommand: cd web/www && yarn install && yarn build
    staticPublishPath: web/www/dist
    buildFilter:
      paths:
        - web/wwww/**/*.ts
        - web/www/*.json
    envVars:
      - fromGroup: web/www
      - key: VITE_PUBLIC_API_BASE_URL
        value: https://v1.api.grambot.fun
    domains:
      - grambot.fun
databases:
  - name: safeguardDB
    plan: free
